[tool.poetry]
name = "ocr"
version = "0.0.0"
description = "Projet d'alimentation de la pipeline consore"
authors = ["DataFactory"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.11.7,<3.13"
pythontoolbox = "2.0.9"
pandas = "^2.2.1"
geopandas = "0.14.4"



[[tool.poetry.source]]
name = "nexus"
url = "https://nexus-data.curie.net/repository/pypi/simple/"
priority = "supplemental"
